/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List agents */
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get agent by ID */
        get: operations["getAgentDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}/uptime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get agent uptime SLA (aggregated from monitors) */
        get: operations["getAgentUptime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get agent health */
        get: operations["getAgentHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get agent reports (paginated) */
        get: operations["getAgentReports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}/monitors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List monitors for an agent */
        get: operations["listMonitors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get monitor by ID */
        get: operations["getMonitorDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitors/{id}/uptime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get monitor uptime SLA (daily buckets and percent) */
        get: operations["getMonitorUptime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/monitors/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get monitor report history */
        get: operations["getMonitorHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System health summary */
        get: operations["getSystemHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health issues (down/degraded/stale) */
        get: operations["getHealthIssues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Incident candidates (down/degraded with severity) */
        get: operations["getIncidentCandidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiEnvelope: {
            success: boolean;
            message: string;
            data?: unknown;
            error?: string;
        };
        ApiError: components["schemas"]["ApiEnvelope"] & {
            /** @constant */
            success?: false;
            error?: string;
        };
        GeoLocation: {
            ip?: string;
            hostname?: string;
            city?: string;
            region?: string;
            country?: string;
            loc?: string;
            org?: string;
            postal?: string;
            timezone?: string;
        };
        CPUStats: {
            cores?: number;
            usage_percent?: number;
            load_1?: number;
            load_5?: number;
            load_15?: number;
        };
        MemoryStats: {
            total_bytes?: number;
            used_bytes?: number;
            free_bytes?: number;
            available_bytes?: number;
            used_percent?: number;
        };
        DiskStats: {
            total_bytes?: number;
            used_bytes?: number;
            free_bytes?: number;
            used_percent?: number;
        };
        Agent: {
            id?: string;
            machine_id?: string;
            name?: string;
            os?: string;
            platform?: string;
            kernel_version?: string;
            arch?: string;
            maintenance_mode?: boolean;
            reporting_interval_seconds?: number;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            deleted_at?: string | null;
            /** Format: date-time */
            last_seen?: string;
            location?: components["schemas"]["GeoLocation"];
            meta?: string;
            /** @description Present in list response */
            monitor_count?: number;
            /** @description From latest AgentReport.Location.IP */
            ip?: string | null;
            /** @description From latest AgentReport */
            uptime_seconds?: number | null;
        };
        AgentReport: {
            id?: string;
            agent_id?: string;
            /** Format: date-time */
            created_at?: string;
            uptime_seconds?: number;
            timestamp?: string;
            cpu?: components["schemas"]["CPUStats"];
            memory?: components["schemas"]["MemoryStats"];
            disk?: components["schemas"]["DiskStats"];
            location?: components["schemas"]["GeoLocation"];
        };
        Monitor: {
            id?: string;
            description?: string | null;
            type?: string;
            name?: string;
            agent_id?: string;
            /** Format: date-time */
            last_successful_report_at?: string | null;
            reporting_interval_seconds?: number;
            computed_health?: string;
            /** Format: date-time */
            last_health_computation?: string | null;
            lifecycle?: string;
            health?: string;
            meta?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            /** Format: date-time */
            deleted_at?: string | null;
        };
        MonitorReport: {
            id?: string;
            monitor_id?: string;
            payload?: string;
            collected_at?: string;
            health?: string;
            /** Format: date-time */
            created_at?: string;
        };
        ListAgentsResponse: components["schemas"]["ApiEnvelope"] & {
            data?: {
                agents?: components["schemas"]["Agent"][];
                count?: number;
                limit?: number;
                offset?: number;
            };
        };
        GetAgentDetailResponse: components["schemas"]["ApiEnvelope"] & {
            data?: {
                agent?: components["schemas"]["Agent"];
                latest_report?: components["schemas"]["AgentReport"] | null;
            };
        };
        GetAgentHealthResponse: components["schemas"]["ApiEnvelope"] & {
            data?: {
                agent_id?: string;
                overall_health?: string;
                up_count?: number;
                down_count?: number;
                degraded_count?: number;
            };
        };
        /** @description One day in the SLA heatmap */
        UptimeDayBucket: {
            /** Format: date */
            date?: string;
            up?: number;
            total?: number;
            uptime_percent?: number;
        };
        GetUptimeResponse: components["schemas"]["ApiEnvelope"] & {
            data?: {
                daily_buckets?: components["schemas"]["UptimeDayBucket"][];
                uptime_percent?: number;
            };
        };
        GetAgentReportsResponse: components["schemas"]["ApiEnvelope"] & {
            data?: {
                reports?: components["schemas"]["AgentReport"][];
                count?: number;
                limit?: number;
                offset?: number;
            };
        };
        ListMonitorsResponse: components["schemas"]["ApiEnvelope"] & {
            data?: {
                monitors?: components["schemas"]["Monitor"][];
                count?: number;
                limit?: number;
                offset?: number;
            };
        };
        GetMonitorDetailResponse: components["schemas"]["ApiEnvelope"] & {
            data?: {
                monitor?: components["schemas"]["Monitor"];
                recent_reports?: components["schemas"]["MonitorReport"][];
                computed_health?: string;
            };
        };
        GetMonitorHistoryResponse: components["schemas"]["ApiEnvelope"] & {
            data?: {
                reports?: components["schemas"]["MonitorReport"][];
                count?: number;
                limit?: number;
                offset?: number;
            };
        };
        GetSystemHealthResponse: components["schemas"]["ApiEnvelope"] & {
            data?: {
                overall_health?: string;
                agents?: {
                    total?: number;
                };
                monitors?: {
                    total?: number;
                    up?: number;
                    down?: number;
                    degraded?: number;
                    unknown?: number;
                };
            };
        };
        HealthIssue: {
            monitor_id?: string;
            monitor_name?: string;
            monitor_type?: string;
            health?: string;
            agent_id?: string;
            agent_name?: string;
            issue_type?: string;
        };
        GetHealthIssuesResponse: components["schemas"]["ApiEnvelope"] & {
            data?: {
                issues?: components["schemas"]["HealthIssue"][];
                count?: number;
            };
        };
        IncidentCandidate: {
            monitor_id?: string;
            monitor_name?: string;
            monitor_type?: string;
            health?: string;
            severity?: string;
            agent_id?: string;
            agent_name?: string;
            down_count?: number;
        };
        GetIncidentCandidatesResponse: components["schemas"]["ApiEnvelope"] & {
            data?: {
                candidates?: components["schemas"]["IncidentCandidate"][];
                count?: number;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAgents: {
        parameters: {
            query?: {
                /** @description Search by name, machine_id, or meta */
                search?: string;
                /** @description Filter by health (up, down, degraded, unknown) */
                status?: "up" | "down" | "degraded" | "unknown";
                /** @description Filter by last seen (e.g. 24h, 7d) */
                last_seen?: string;
                /** @description Filter by uptime threshold */
                uptime?: string;
                /** @description Sort field (name, last_seen, uptime_seconds, monitor_count, etc.) */
                sort?: string;
                order?: "asc" | "desc";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agents and pagination */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAgentsResponse"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getAgentDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent and latest report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAgentDetailResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Agent not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getAgentUptime: {
        parameters: {
            query?: {
                /** @description e.g. 90d, 30d */
                period?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily buckets and uptime_percent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetUptimeResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getAgentHealth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent health counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAgentHealthResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getAgentReports: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reports and pagination */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAgentReportsResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listMonitors: {
        parameters: {
            query?: {
                health?: string;
                lifecycle?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Monitors and pagination */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMonitorsResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getMonitorDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Monitor, recent reports, computed health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetMonitorDetailResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getMonitorUptime: {
        parameters: {
            query?: {
                /** @description e.g. 90d, 30d */
                period?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily buckets and uptime_percent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetUptimeResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getMonitorHistory: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reports and pagination */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetMonitorHistoryResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getSystemHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Overall health and monitor counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetSystemHealthResponse"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getHealthIssues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of issues */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetHealthIssuesResponse"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getIncidentCandidates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of candidates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetIncidentCandidatesResponse"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
