package config

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"gopkg.in/yaml.v3"
)

type InternalState struct {
	AgentID      string        `yaml:"agent_id"`     // Agent ID; generated by core on registration
	Token        string        `yaml:"token"`        // Auth token for API calls
	Registered   bool          `yaml:"registered"`   // Whether the agent has been registered
	CoreURL      string        `yaml:"core_url"`     // Core server endpoint
	LastSync     time.Time     `yaml:"last_sync"`    // Last sync time
	Applications []Application `yaml:"applications"` // Applications
}

type Application struct {
	Name        string    `yaml:"name"`
	ID          string    `yaml:"id"`
	Status      string    `yaml:"status"`
	LastError   string    `yaml:"last_error"`
	LastChecked time.Time `yaml:"last_checked"`
	NextCheck   time.Time `yaml:"next_check"`
}

type SubProcess struct {
	Name string `yaml:"name"`
	Cmd  string `yaml:"cmd"`
}

type Config struct {
	AgentID      string       `yaml:"agent_id"`     // Agent ID; generated by core on registration
	CoreURL      string       `yaml:"core_url"`     // Core server endpoint
	Token        string       `yaml:"token"`        // Auth token for API calls
	Interval     string       `yaml:"interval"`     // e.g., "60s", "5m"
	SubProcesses []SubProcess `yaml:"subprocesses"` // Optional subprocess definitions
}

func Load(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("failed to read config file: %w", err)
	}

	var cfg Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("failed to parse config: %w", err)
	}

	if err := cfg.Validate(); err != nil {
		return nil, fmt.Errorf("invalid config: %w", err)
	}

	return &cfg, nil
}

// Validate checks that required fields are set and the interval is valid.
// For initial registration, agent_id and token are optional.
func (c *Config) Validate() error {
	if c.CoreURL == "" {
		return errors.New("core_url is required")
	}
	if c.Interval == "" {
		return errors.New("interval is required")
	}
	if _, err := time.ParseDuration(c.Interval); err != nil {
		return fmt.Errorf("invalid interval format: %w", err)
	}
	return nil
}

// IsRegistered checks if the agent has been registered (has agent_id and token)
func (c *Config) IsRegistered() bool {
	return c.AgentID != "" && c.Token != ""
}

// Save writes the config to the specified path
func (c *Config) Save(path string) error {
	data, err := yaml.Marshal(c)
	if err != nil {
		return fmt.Errorf("failed to marshal config: %w", err)
	}

	if err := os.WriteFile(path, data, 0644); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	return nil
}

// UpdateRegistration updates the config with registration data
func (c *Config) UpdateRegistration(agentID string, token string) {
	c.AgentID = agentID
	c.Token = token
}

// DefaultPath returns the default path for the agent config.
// On Linux: /etc/orion/config.yaml
// On macOS: /usr/local/etc/orion/config.yaml
func DefaultPath() string {
	// Try Linux-style first
	if _, err := os.Stat("/etc/orion/config.yaml"); err == nil {
		return "/etc/orion/config.yaml"
	}

	// Fallback for macOS
	if _, err := os.Stat("/usr/local/etc/orion/config.yaml"); err == nil {
		return "/usr/local/etc/orion/config.yaml"
	}

	// Fallback to current working directory
	cwd, _ := os.Getwd()
	return filepath.Join(cwd, "config.yaml")
}
