core_url: http://localhost:8999
interval: 5s
monitors:
  - name: ibis-server
    description: backend server for ibis
    type: "http-healthcheck"
    interval: 2s
    http:
      url: "https://ibis.thesunday.studio/api/health"
      timeout: 3s
      expected_status: 200
  - name: orion-server
    description: orion core service
    type: "internal-service"
    interval: 5s
    internal_service:
      ping:
        url: "http://localhost:8999/health"
        timeout: 3s
      process:
        port: 8999
  - name: orion-website
    description: orion website
    type: "website"
    interval: 5s
    website:
      url: "https://thesunday.studio"
      timeout: 3s
      expected_status: 200
