/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * Orion Core API
 * Frontend-facing API for Orion. Covers only frontend routes (no agent-protected POST endpoints).
All responses use the envelope `{ success, message, data?, error? }`.

 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from './custom-instance';
import type { ErrorType } from './custom-instance';
export interface ApiEnvelope {
  success: boolean;
  message: string;
  data?: unknown;
  error?: string;
}

export interface ApiError {
  success: boolean;
  message: string;
  error?: string;
}

export interface GeoLocation {
  ip?: string;
  hostname?: string;
  city?: string;
  region?: string;
  country?: string;
  loc?: string;
  org?: string;
  postal?: string;
  timezone?: string;
}

export interface CPUStats {
  cores?: number;
  usage_percent?: number;
  load_1?: number;
  load_5?: number;
  load_15?: number;
}

export interface MemoryStats {
  total_bytes?: number;
  used_bytes?: number;
  free_bytes?: number;
  available_bytes?: number;
  used_percent?: number;
}

export interface DiskStats {
  total_bytes?: number;
  used_bytes?: number;
  free_bytes?: number;
  used_percent?: number;
}

export interface Agent {
  id?: string;
  machine_id?: string;
  name?: string;
  os?: string;
  platform?: string;
  kernel_version?: string;
  arch?: string;
  maintenance_mode?: boolean;
  reporting_interval_seconds?: number;
  created_at?: string;
  /** @nullable */
  deleted_at?: string | null;
  last_seen?: string;
  location?: GeoLocation;
  meta?: string;
  /** Present in list response */
  monitor_count?: number;
  /**
   * From latest AgentReport.Location.IP
   * @nullable
   */
  ip?: string | null;
  /**
   * From latest AgentReport
   * @nullable
   */
  uptime_seconds?: number | null;
}

export interface AgentReport {
  id?: string;
  agent_id?: string;
  created_at?: string;
  uptime_seconds?: number;
  timestamp?: string;
  cpu?: CPUStats;
  memory?: MemoryStats;
  disk?: DiskStats;
  location?: GeoLocation;
}

export interface Monitor {
  id?: string;
  /** @nullable */
  description?: string | null;
  type?: string;
  name?: string;
  agent_id?: string;
  /** @nullable */
  last_successful_report_at?: string | null;
  reporting_interval_seconds?: number;
  computed_health?: string;
  /** @nullable */
  last_health_computation?: string | null;
  lifecycle?: string;
  health?: string;
  meta?: string;
  created_at?: string;
  updated_at?: string;
  /** @nullable */
  deleted_at?: string | null;
}

export interface MonitorReport {
  id?: string;
  monitor_id?: string;
  payload?: string;
  collected_at?: string;
  health?: string;
  created_at?: string;
}

export type ListAgentsResponseData = {
  agents?: Agent[];
  count?: number;
  limit?: number;
  offset?: number;
};

export interface ListAgentsResponse {
  success: boolean;
  message: string;
  data?: ListAgentsResponseData;
}

export type GetAgentDetailResponseData = {
  agent?: Agent;
  latest_report?: AgentReport;
};

export interface GetAgentDetailResponse {
  success: boolean;
  message: string;
  data?: GetAgentDetailResponseData;
}

export type GetAgentHealthResponseData = {
  agent_id?: string;
  overall_health?: string;
  up_count?: number;
  down_count?: number;
  degraded_count?: number;
};

export interface GetAgentHealthResponse {
  success: boolean;
  message: string;
  data?: GetAgentHealthResponseData;
}

/**
 * One day in the SLA heatmap
 */
export interface UptimeDayBucket {
  date?: string;
  up?: number;
  total?: number;
  uptime_percent?: number;
}

export type GetUptimeResponseData = {
  daily_buckets?: UptimeDayBucket[];
  uptime_percent?: number;
};

export interface GetUptimeResponse {
  success: boolean;
  message: string;
  data?: GetUptimeResponseData;
}

export type GetAgentReportsResponseData = {
  reports?: AgentReport[];
  count?: number;
  limit?: number;
  offset?: number;
};

export interface GetAgentReportsResponse {
  success: boolean;
  message: string;
  data?: GetAgentReportsResponseData;
}

export type ListMonitorsResponseData = {
  monitors?: Monitor[];
  count?: number;
  limit?: number;
  offset?: number;
};

export interface ListMonitorsResponse {
  success: boolean;
  message: string;
  data?: ListMonitorsResponseData;
}

export type GetMonitorDetailResponseData = {
  monitor?: Monitor;
  recent_reports?: MonitorReport[];
  computed_health?: string;
};

export interface GetMonitorDetailResponse {
  success: boolean;
  message: string;
  data?: GetMonitorDetailResponseData;
}

export type GetMonitorHistoryResponseData = {
  reports?: MonitorReport[];
  count?: number;
  limit?: number;
  offset?: number;
};

export interface GetMonitorHistoryResponse {
  success: boolean;
  message: string;
  data?: GetMonitorHistoryResponseData;
}

export type GetSystemHealthResponseDataAgents = {
  total?: number;
};

export type GetSystemHealthResponseDataMonitors = {
  total?: number;
  up?: number;
  down?: number;
  degraded?: number;
  unknown?: number;
};

export type GetSystemHealthResponseData = {
  overall_health?: string;
  agents?: GetSystemHealthResponseDataAgents;
  monitors?: GetSystemHealthResponseDataMonitors;
};

export interface GetSystemHealthResponse {
  success: boolean;
  message: string;
  data?: GetSystemHealthResponseData;
}

export interface HealthIssue {
  monitor_id?: string;
  monitor_name?: string;
  monitor_type?: string;
  health?: string;
  agent_id?: string;
  agent_name?: string;
  issue_type?: string;
}

export type GetHealthIssuesResponseData = {
  issues?: HealthIssue[];
  count?: number;
};

export interface GetHealthIssuesResponse {
  success: boolean;
  message: string;
  data?: GetHealthIssuesResponseData;
}

export interface IncidentCandidate {
  monitor_id?: string;
  monitor_name?: string;
  monitor_type?: string;
  health?: string;
  severity?: string;
  agent_id?: string;
  agent_name?: string;
  down_count?: number;
}

export type GetIncidentCandidatesResponseData = {
  candidates?: IncidentCandidate[];
  count?: number;
};

export interface GetIncidentCandidatesResponse {
  success: boolean;
  message: string;
  data?: GetIncidentCandidatesResponseData;
}

export type ListAgentsParams = {
/**
 * Search by name, machine_id, or meta
 */
search?: string;
/**
 * Filter by health (up, down, degraded, unknown)
 */
status?: ListAgentsStatus;
/**
 * Filter by last seen (e.g. 24h, 7d)
 */
last_seen?: string;
/**
 * Filter by uptime threshold
 */
uptime?: string;
/**
 * Sort field (name, last_seen, uptime_seconds, monitor_count, etc.)
 */
sort?: string;
order?: ListAgentsOrder;
limit?: number;
offset?: number;
};

export type ListAgentsStatus = typeof ListAgentsStatus[keyof typeof ListAgentsStatus];


export const ListAgentsStatus = {
  up: 'up',
  down: 'down',
  degraded: 'degraded',
  unknown: 'unknown',
} as const;

export type ListAgentsOrder = typeof ListAgentsOrder[keyof typeof ListAgentsOrder];


export const ListAgentsOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type GetAgentUptimeParams = {
/**
 * e.g. 90d, 30d
 */
period?: string;
};

export type GetAgentReportsParams = {
limit?: number;
offset?: number;
};

export type ListMonitorsParams = {
health?: string;
lifecycle?: string;
limit?: number;
offset?: number;
};

export type GetMonitorUptimeParams = {
/**
 * e.g. 90d, 30d
 */
period?: string;
};

export type GetMonitorHistoryParams = {
limit?: number;
offset?: number;
};

/**
 * @summary List agents
 */
export type listAgentsResponse200 = {
  data: ListAgentsResponse
  status: 200
}

export type listAgentsResponse500 = {
  data: void
  status: 500
}
    
export type listAgentsResponseSuccess = (listAgentsResponse200) & {
  headers: Headers;
};
export type listAgentsResponseError = (listAgentsResponse500) & {
  headers: Headers;
};

export type listAgentsResponse = (listAgentsResponseSuccess | listAgentsResponseError)

export const getListAgentsUrl = (params?: ListAgentsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/agents?${stringifiedParams}` : `/agents`
}

export const listAgents = async (params?: ListAgentsParams, options?: RequestInit): Promise<listAgentsResponse> => {
  
  return customInstance<listAgentsResponse>(getListAgentsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListAgentsQueryKey = (params?: ListAgentsParams,) => {
    return [
    `/agents`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListAgentsQueryOptions = <TData = Awaited<ReturnType<typeof listAgents>>, TError = ErrorType<void>>(params?: ListAgentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAgents>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAgentsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAgents>>> = ({ signal }) => listAgents(params, { signal });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAgents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAgentsQueryResult = NonNullable<Awaited<ReturnType<typeof listAgents>>>
export type ListAgentsQueryError = ErrorType<void>


export function useListAgents<TData = Awaited<ReturnType<typeof listAgents>>, TError = ErrorType<void>>(
 params: undefined |  ListAgentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAgents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAgents>>,
          TError,
          Awaited<ReturnType<typeof listAgents>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAgents<TData = Awaited<ReturnType<typeof listAgents>>, TError = ErrorType<void>>(
 params?: ListAgentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAgents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAgents>>,
          TError,
          Awaited<ReturnType<typeof listAgents>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAgents<TData = Awaited<ReturnType<typeof listAgents>>, TError = ErrorType<void>>(
 params?: ListAgentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAgents>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List agents
 */

export function useListAgents<TData = Awaited<ReturnType<typeof listAgents>>, TError = ErrorType<void>>(
 params?: ListAgentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAgents>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAgentsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Get agent by ID
 */
export type getAgentDetailResponse200 = {
  data: GetAgentDetailResponse
  status: 200
}

export type getAgentDetailResponse400 = {
  data: void
  status: 400
}

export type getAgentDetailResponse404 = {
  data: void
  status: 404
}
    
export type getAgentDetailResponseSuccess = (getAgentDetailResponse200) & {
  headers: Headers;
};
export type getAgentDetailResponseError = (getAgentDetailResponse400 | getAgentDetailResponse404) & {
  headers: Headers;
};

export type getAgentDetailResponse = (getAgentDetailResponseSuccess | getAgentDetailResponseError)

export const getGetAgentDetailUrl = (id: string,) => {


  

  return `/agents/${id}`
}

export const getAgentDetail = async (id: string, options?: RequestInit): Promise<getAgentDetailResponse> => {
  
  return customInstance<getAgentDetailResponse>(getGetAgentDetailUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAgentDetailQueryKey = (id: string,) => {
    return [
    `/agents/${id}`
    ] as const;
    }

    
export const getGetAgentDetailQueryOptions = <TData = Awaited<ReturnType<typeof getAgentDetail>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentDetail>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAgentDetailQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAgentDetail>>> = ({ signal }) => getAgentDetail(id, { signal });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAgentDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAgentDetailQueryResult = NonNullable<Awaited<ReturnType<typeof getAgentDetail>>>
export type GetAgentDetailQueryError = ErrorType<void>


export function useGetAgentDetail<TData = Awaited<ReturnType<typeof getAgentDetail>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAgentDetail>>,
          TError,
          Awaited<ReturnType<typeof getAgentDetail>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAgentDetail<TData = Awaited<ReturnType<typeof getAgentDetail>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAgentDetail>>,
          TError,
          Awaited<ReturnType<typeof getAgentDetail>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAgentDetail<TData = Awaited<ReturnType<typeof getAgentDetail>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentDetail>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get agent by ID
 */

export function useGetAgentDetail<TData = Awaited<ReturnType<typeof getAgentDetail>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentDetail>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAgentDetailQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Get agent uptime SLA (aggregated from monitors)
 */
export type getAgentUptimeResponse200 = {
  data: GetUptimeResponse
  status: 200
}

export type getAgentUptimeResponse400 = {
  data: void
  status: 400
}

export type getAgentUptimeResponse404 = {
  data: void
  status: 404
}

export type getAgentUptimeResponse500 = {
  data: void
  status: 500
}
    
export type getAgentUptimeResponseSuccess = (getAgentUptimeResponse200) & {
  headers: Headers;
};
export type getAgentUptimeResponseError = (getAgentUptimeResponse400 | getAgentUptimeResponse404 | getAgentUptimeResponse500) & {
  headers: Headers;
};

export type getAgentUptimeResponse = (getAgentUptimeResponseSuccess | getAgentUptimeResponseError)

export const getGetAgentUptimeUrl = (id: string,
    params?: GetAgentUptimeParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/agents/${id}/uptime?${stringifiedParams}` : `/agents/${id}/uptime`
}

export const getAgentUptime = async (id: string,
    params?: GetAgentUptimeParams, options?: RequestInit): Promise<getAgentUptimeResponse> => {
  
  return customInstance<getAgentUptimeResponse>(getGetAgentUptimeUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAgentUptimeQueryKey = (id: string,
    params?: GetAgentUptimeParams,) => {
    return [
    `/agents/${id}/uptime`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetAgentUptimeQueryOptions = <TData = Awaited<ReturnType<typeof getAgentUptime>>, TError = ErrorType<void>>(id: string,
    params?: GetAgentUptimeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentUptime>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAgentUptimeQueryKey(id,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAgentUptime>>> = ({ signal }) => getAgentUptime(id,params, { signal });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAgentUptime>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAgentUptimeQueryResult = NonNullable<Awaited<ReturnType<typeof getAgentUptime>>>
export type GetAgentUptimeQueryError = ErrorType<void>


export function useGetAgentUptime<TData = Awaited<ReturnType<typeof getAgentUptime>>, TError = ErrorType<void>>(
 id: string,
    params: undefined |  GetAgentUptimeParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentUptime>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAgentUptime>>,
          TError,
          Awaited<ReturnType<typeof getAgentUptime>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAgentUptime<TData = Awaited<ReturnType<typeof getAgentUptime>>, TError = ErrorType<void>>(
 id: string,
    params?: GetAgentUptimeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentUptime>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAgentUptime>>,
          TError,
          Awaited<ReturnType<typeof getAgentUptime>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAgentUptime<TData = Awaited<ReturnType<typeof getAgentUptime>>, TError = ErrorType<void>>(
 id: string,
    params?: GetAgentUptimeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentUptime>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get agent uptime SLA (aggregated from monitors)
 */

export function useGetAgentUptime<TData = Awaited<ReturnType<typeof getAgentUptime>>, TError = ErrorType<void>>(
 id: string,
    params?: GetAgentUptimeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentUptime>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAgentUptimeQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Get agent health
 */
export type getAgentHealthResponse200 = {
  data: GetAgentHealthResponse
  status: 200
}

export type getAgentHealthResponse400 = {
  data: void
  status: 400
}

export type getAgentHealthResponse404 = {
  data: void
  status: 404
}

export type getAgentHealthResponse500 = {
  data: void
  status: 500
}
    
export type getAgentHealthResponseSuccess = (getAgentHealthResponse200) & {
  headers: Headers;
};
export type getAgentHealthResponseError = (getAgentHealthResponse400 | getAgentHealthResponse404 | getAgentHealthResponse500) & {
  headers: Headers;
};

export type getAgentHealthResponse = (getAgentHealthResponseSuccess | getAgentHealthResponseError)

export const getGetAgentHealthUrl = (id: string,) => {


  

  return `/agents/${id}/health`
}

export const getAgentHealth = async (id: string, options?: RequestInit): Promise<getAgentHealthResponse> => {
  
  return customInstance<getAgentHealthResponse>(getGetAgentHealthUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAgentHealthQueryKey = (id: string,) => {
    return [
    `/agents/${id}/health`
    ] as const;
    }

    
export const getGetAgentHealthQueryOptions = <TData = Awaited<ReturnType<typeof getAgentHealth>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentHealth>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAgentHealthQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAgentHealth>>> = ({ signal }) => getAgentHealth(id, { signal });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAgentHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAgentHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getAgentHealth>>>
export type GetAgentHealthQueryError = ErrorType<void>


export function useGetAgentHealth<TData = Awaited<ReturnType<typeof getAgentHealth>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAgentHealth>>,
          TError,
          Awaited<ReturnType<typeof getAgentHealth>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAgentHealth<TData = Awaited<ReturnType<typeof getAgentHealth>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAgentHealth>>,
          TError,
          Awaited<ReturnType<typeof getAgentHealth>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAgentHealth<TData = Awaited<ReturnType<typeof getAgentHealth>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentHealth>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get agent health
 */

export function useGetAgentHealth<TData = Awaited<ReturnType<typeof getAgentHealth>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentHealth>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAgentHealthQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Get agent reports (paginated)
 */
export type getAgentReportsResponse200 = {
  data: GetAgentReportsResponse
  status: 200
}

export type getAgentReportsResponse400 = {
  data: void
  status: 400
}

export type getAgentReportsResponse404 = {
  data: void
  status: 404
}

export type getAgentReportsResponse500 = {
  data: void
  status: 500
}
    
export type getAgentReportsResponseSuccess = (getAgentReportsResponse200) & {
  headers: Headers;
};
export type getAgentReportsResponseError = (getAgentReportsResponse400 | getAgentReportsResponse404 | getAgentReportsResponse500) & {
  headers: Headers;
};

export type getAgentReportsResponse = (getAgentReportsResponseSuccess | getAgentReportsResponseError)

export const getGetAgentReportsUrl = (id: string,
    params?: GetAgentReportsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/agents/${id}/reports?${stringifiedParams}` : `/agents/${id}/reports`
}

export const getAgentReports = async (id: string,
    params?: GetAgentReportsParams, options?: RequestInit): Promise<getAgentReportsResponse> => {
  
  return customInstance<getAgentReportsResponse>(getGetAgentReportsUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAgentReportsQueryKey = (id: string,
    params?: GetAgentReportsParams,) => {
    return [
    `/agents/${id}/reports`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetAgentReportsQueryOptions = <TData = Awaited<ReturnType<typeof getAgentReports>>, TError = ErrorType<void>>(id: string,
    params?: GetAgentReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentReports>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAgentReportsQueryKey(id,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAgentReports>>> = ({ signal }) => getAgentReports(id,params, { signal });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAgentReports>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAgentReportsQueryResult = NonNullable<Awaited<ReturnType<typeof getAgentReports>>>
export type GetAgentReportsQueryError = ErrorType<void>


export function useGetAgentReports<TData = Awaited<ReturnType<typeof getAgentReports>>, TError = ErrorType<void>>(
 id: string,
    params: undefined |  GetAgentReportsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentReports>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAgentReports>>,
          TError,
          Awaited<ReturnType<typeof getAgentReports>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAgentReports<TData = Awaited<ReturnType<typeof getAgentReports>>, TError = ErrorType<void>>(
 id: string,
    params?: GetAgentReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentReports>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAgentReports>>,
          TError,
          Awaited<ReturnType<typeof getAgentReports>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAgentReports<TData = Awaited<ReturnType<typeof getAgentReports>>, TError = ErrorType<void>>(
 id: string,
    params?: GetAgentReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentReports>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get agent reports (paginated)
 */

export function useGetAgentReports<TData = Awaited<ReturnType<typeof getAgentReports>>, TError = ErrorType<void>>(
 id: string,
    params?: GetAgentReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentReports>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAgentReportsQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary List monitors for an agent
 */
export type listMonitorsResponse200 = {
  data: ListMonitorsResponse
  status: 200
}

export type listMonitorsResponse400 = {
  data: void
  status: 400
}

export type listMonitorsResponse500 = {
  data: void
  status: 500
}
    
export type listMonitorsResponseSuccess = (listMonitorsResponse200) & {
  headers: Headers;
};
export type listMonitorsResponseError = (listMonitorsResponse400 | listMonitorsResponse500) & {
  headers: Headers;
};

export type listMonitorsResponse = (listMonitorsResponseSuccess | listMonitorsResponseError)

export const getListMonitorsUrl = (id: string,
    params?: ListMonitorsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/agents/${id}/monitors?${stringifiedParams}` : `/agents/${id}/monitors`
}

export const listMonitors = async (id: string,
    params?: ListMonitorsParams, options?: RequestInit): Promise<listMonitorsResponse> => {
  
  return customInstance<listMonitorsResponse>(getListMonitorsUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListMonitorsQueryKey = (id: string,
    params?: ListMonitorsParams,) => {
    return [
    `/agents/${id}/monitors`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListMonitorsQueryOptions = <TData = Awaited<ReturnType<typeof listMonitors>>, TError = ErrorType<void>>(id: string,
    params?: ListMonitorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMonitors>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMonitorsQueryKey(id,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMonitors>>> = ({ signal }) => listMonitors(id,params, { signal });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMonitors>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMonitorsQueryResult = NonNullable<Awaited<ReturnType<typeof listMonitors>>>
export type ListMonitorsQueryError = ErrorType<void>


export function useListMonitors<TData = Awaited<ReturnType<typeof listMonitors>>, TError = ErrorType<void>>(
 id: string,
    params: undefined |  ListMonitorsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMonitors>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMonitors>>,
          TError,
          Awaited<ReturnType<typeof listMonitors>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMonitors<TData = Awaited<ReturnType<typeof listMonitors>>, TError = ErrorType<void>>(
 id: string,
    params?: ListMonitorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMonitors>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMonitors>>,
          TError,
          Awaited<ReturnType<typeof listMonitors>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMonitors<TData = Awaited<ReturnType<typeof listMonitors>>, TError = ErrorType<void>>(
 id: string,
    params?: ListMonitorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMonitors>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List monitors for an agent
 */

export function useListMonitors<TData = Awaited<ReturnType<typeof listMonitors>>, TError = ErrorType<void>>(
 id: string,
    params?: ListMonitorsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMonitors>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMonitorsQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Get monitor by ID
 */
export type getMonitorDetailResponse200 = {
  data: GetMonitorDetailResponse
  status: 200
}

export type getMonitorDetailResponse400 = {
  data: void
  status: 400
}

export type getMonitorDetailResponse404 = {
  data: void
  status: 404
}
    
export type getMonitorDetailResponseSuccess = (getMonitorDetailResponse200) & {
  headers: Headers;
};
export type getMonitorDetailResponseError = (getMonitorDetailResponse400 | getMonitorDetailResponse404) & {
  headers: Headers;
};

export type getMonitorDetailResponse = (getMonitorDetailResponseSuccess | getMonitorDetailResponseError)

export const getGetMonitorDetailUrl = (id: string,) => {


  

  return `/monitors/${id}`
}

export const getMonitorDetail = async (id: string, options?: RequestInit): Promise<getMonitorDetailResponse> => {
  
  return customInstance<getMonitorDetailResponse>(getGetMonitorDetailUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMonitorDetailQueryKey = (id: string,) => {
    return [
    `/monitors/${id}`
    ] as const;
    }

    
export const getGetMonitorDetailQueryOptions = <TData = Awaited<ReturnType<typeof getMonitorDetail>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonitorDetail>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMonitorDetailQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMonitorDetail>>> = ({ signal }) => getMonitorDetail(id, { signal });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMonitorDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMonitorDetailQueryResult = NonNullable<Awaited<ReturnType<typeof getMonitorDetail>>>
export type GetMonitorDetailQueryError = ErrorType<void>


export function useGetMonitorDetail<TData = Awaited<ReturnType<typeof getMonitorDetail>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonitorDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMonitorDetail>>,
          TError,
          Awaited<ReturnType<typeof getMonitorDetail>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMonitorDetail<TData = Awaited<ReturnType<typeof getMonitorDetail>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonitorDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMonitorDetail>>,
          TError,
          Awaited<ReturnType<typeof getMonitorDetail>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMonitorDetail<TData = Awaited<ReturnType<typeof getMonitorDetail>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonitorDetail>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get monitor by ID
 */

export function useGetMonitorDetail<TData = Awaited<ReturnType<typeof getMonitorDetail>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonitorDetail>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMonitorDetailQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Get monitor uptime SLA (daily buckets and percent)
 */
export type getMonitorUptimeResponse200 = {
  data: GetUptimeResponse
  status: 200
}

export type getMonitorUptimeResponse400 = {
  data: void
  status: 400
}

export type getMonitorUptimeResponse404 = {
  data: void
  status: 404
}

export type getMonitorUptimeResponse500 = {
  data: void
  status: 500
}
    
export type getMonitorUptimeResponseSuccess = (getMonitorUptimeResponse200) & {
  headers: Headers;
};
export type getMonitorUptimeResponseError = (getMonitorUptimeResponse400 | getMonitorUptimeResponse404 | getMonitorUptimeResponse500) & {
  headers: Headers;
};

export type getMonitorUptimeResponse = (getMonitorUptimeResponseSuccess | getMonitorUptimeResponseError)

export const getGetMonitorUptimeUrl = (id: string,
    params?: GetMonitorUptimeParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/monitors/${id}/uptime?${stringifiedParams}` : `/monitors/${id}/uptime`
}

export const getMonitorUptime = async (id: string,
    params?: GetMonitorUptimeParams, options?: RequestInit): Promise<getMonitorUptimeResponse> => {
  
  return customInstance<getMonitorUptimeResponse>(getGetMonitorUptimeUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMonitorUptimeQueryKey = (id: string,
    params?: GetMonitorUptimeParams,) => {
    return [
    `/monitors/${id}/uptime`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetMonitorUptimeQueryOptions = <TData = Awaited<ReturnType<typeof getMonitorUptime>>, TError = ErrorType<void>>(id: string,
    params?: GetMonitorUptimeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonitorUptime>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMonitorUptimeQueryKey(id,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMonitorUptime>>> = ({ signal }) => getMonitorUptime(id,params, { signal });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMonitorUptime>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMonitorUptimeQueryResult = NonNullable<Awaited<ReturnType<typeof getMonitorUptime>>>
export type GetMonitorUptimeQueryError = ErrorType<void>


export function useGetMonitorUptime<TData = Awaited<ReturnType<typeof getMonitorUptime>>, TError = ErrorType<void>>(
 id: string,
    params: undefined |  GetMonitorUptimeParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonitorUptime>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMonitorUptime>>,
          TError,
          Awaited<ReturnType<typeof getMonitorUptime>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMonitorUptime<TData = Awaited<ReturnType<typeof getMonitorUptime>>, TError = ErrorType<void>>(
 id: string,
    params?: GetMonitorUptimeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonitorUptime>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMonitorUptime>>,
          TError,
          Awaited<ReturnType<typeof getMonitorUptime>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMonitorUptime<TData = Awaited<ReturnType<typeof getMonitorUptime>>, TError = ErrorType<void>>(
 id: string,
    params?: GetMonitorUptimeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonitorUptime>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get monitor uptime SLA (daily buckets and percent)
 */

export function useGetMonitorUptime<TData = Awaited<ReturnType<typeof getMonitorUptime>>, TError = ErrorType<void>>(
 id: string,
    params?: GetMonitorUptimeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonitorUptime>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMonitorUptimeQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Get monitor report history
 */
export type getMonitorHistoryResponse200 = {
  data: GetMonitorHistoryResponse
  status: 200
}

export type getMonitorHistoryResponse400 = {
  data: void
  status: 400
}

export type getMonitorHistoryResponse500 = {
  data: void
  status: 500
}
    
export type getMonitorHistoryResponseSuccess = (getMonitorHistoryResponse200) & {
  headers: Headers;
};
export type getMonitorHistoryResponseError = (getMonitorHistoryResponse400 | getMonitorHistoryResponse500) & {
  headers: Headers;
};

export type getMonitorHistoryResponse = (getMonitorHistoryResponseSuccess | getMonitorHistoryResponseError)

export const getGetMonitorHistoryUrl = (id: string,
    params?: GetMonitorHistoryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/monitors/${id}/history?${stringifiedParams}` : `/monitors/${id}/history`
}

export const getMonitorHistory = async (id: string,
    params?: GetMonitorHistoryParams, options?: RequestInit): Promise<getMonitorHistoryResponse> => {
  
  return customInstance<getMonitorHistoryResponse>(getGetMonitorHistoryUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMonitorHistoryQueryKey = (id: string,
    params?: GetMonitorHistoryParams,) => {
    return [
    `/monitors/${id}/history`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetMonitorHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getMonitorHistory>>, TError = ErrorType<void>>(id: string,
    params?: GetMonitorHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonitorHistory>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMonitorHistoryQueryKey(id,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMonitorHistory>>> = ({ signal }) => getMonitorHistory(id,params, { signal });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMonitorHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMonitorHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getMonitorHistory>>>
export type GetMonitorHistoryQueryError = ErrorType<void>


export function useGetMonitorHistory<TData = Awaited<ReturnType<typeof getMonitorHistory>>, TError = ErrorType<void>>(
 id: string,
    params: undefined |  GetMonitorHistoryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonitorHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMonitorHistory>>,
          TError,
          Awaited<ReturnType<typeof getMonitorHistory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMonitorHistory<TData = Awaited<ReturnType<typeof getMonitorHistory>>, TError = ErrorType<void>>(
 id: string,
    params?: GetMonitorHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonitorHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMonitorHistory>>,
          TError,
          Awaited<ReturnType<typeof getMonitorHistory>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMonitorHistory<TData = Awaited<ReturnType<typeof getMonitorHistory>>, TError = ErrorType<void>>(
 id: string,
    params?: GetMonitorHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonitorHistory>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get monitor report history
 */

export function useGetMonitorHistory<TData = Awaited<ReturnType<typeof getMonitorHistory>>, TError = ErrorType<void>>(
 id: string,
    params?: GetMonitorHistoryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMonitorHistory>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMonitorHistoryQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary System health summary
 */
export type getSystemHealthResponse200 = {
  data: GetSystemHealthResponse
  status: 200
}

export type getSystemHealthResponse500 = {
  data: void
  status: 500
}
    
export type getSystemHealthResponseSuccess = (getSystemHealthResponse200) & {
  headers: Headers;
};
export type getSystemHealthResponseError = (getSystemHealthResponse500) & {
  headers: Headers;
};

export type getSystemHealthResponse = (getSystemHealthResponseSuccess | getSystemHealthResponseError)

export const getGetSystemHealthUrl = () => {


  

  return `/health/summary`
}

export const getSystemHealth = async ( options?: RequestInit): Promise<getSystemHealthResponse> => {
  
  return customInstance<getSystemHealthResponse>(getGetSystemHealthUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetSystemHealthQueryKey = () => {
    return [
    `/health/summary`
    ] as const;
    }

    
export const getGetSystemHealthQueryOptions = <TData = Awaited<ReturnType<typeof getSystemHealth>>, TError = ErrorType<void>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemHealth>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSystemHealthQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSystemHealth>>> = ({ signal }) => getSystemHealth({ signal });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSystemHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSystemHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getSystemHealth>>>
export type GetSystemHealthQueryError = ErrorType<void>


export function useGetSystemHealth<TData = Awaited<ReturnType<typeof getSystemHealth>>, TError = ErrorType<void>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSystemHealth>>,
          TError,
          Awaited<ReturnType<typeof getSystemHealth>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSystemHealth<TData = Awaited<ReturnType<typeof getSystemHealth>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSystemHealth>>,
          TError,
          Awaited<ReturnType<typeof getSystemHealth>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSystemHealth<TData = Awaited<ReturnType<typeof getSystemHealth>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemHealth>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary System health summary
 */

export function useGetSystemHealth<TData = Awaited<ReturnType<typeof getSystemHealth>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSystemHealth>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSystemHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Health issues (down/degraded/stale)
 */
export type getHealthIssuesResponse200 = {
  data: GetHealthIssuesResponse
  status: 200
}

export type getHealthIssuesResponse500 = {
  data: void
  status: 500
}
    
export type getHealthIssuesResponseSuccess = (getHealthIssuesResponse200) & {
  headers: Headers;
};
export type getHealthIssuesResponseError = (getHealthIssuesResponse500) & {
  headers: Headers;
};

export type getHealthIssuesResponse = (getHealthIssuesResponseSuccess | getHealthIssuesResponseError)

export const getGetHealthIssuesUrl = () => {


  

  return `/health/issues`
}

export const getHealthIssues = async ( options?: RequestInit): Promise<getHealthIssuesResponse> => {
  
  return customInstance<getHealthIssuesResponse>(getGetHealthIssuesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetHealthIssuesQueryKey = () => {
    return [
    `/health/issues`
    ] as const;
    }

    
export const getGetHealthIssuesQueryOptions = <TData = Awaited<ReturnType<typeof getHealthIssues>>, TError = ErrorType<void>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealthIssues>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHealthIssuesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealthIssues>>> = ({ signal }) => getHealthIssues({ signal });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHealthIssues>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHealthIssuesQueryResult = NonNullable<Awaited<ReturnType<typeof getHealthIssues>>>
export type GetHealthIssuesQueryError = ErrorType<void>


export function useGetHealthIssues<TData = Awaited<ReturnType<typeof getHealthIssues>>, TError = ErrorType<void>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealthIssues>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealthIssues>>,
          TError,
          Awaited<ReturnType<typeof getHealthIssues>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealthIssues<TData = Awaited<ReturnType<typeof getHealthIssues>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealthIssues>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealthIssues>>,
          TError,
          Awaited<ReturnType<typeof getHealthIssues>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealthIssues<TData = Awaited<ReturnType<typeof getHealthIssues>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealthIssues>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health issues (down/degraded/stale)
 */

export function useGetHealthIssues<TData = Awaited<ReturnType<typeof getHealthIssues>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealthIssues>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHealthIssuesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Incident candidates (down/degraded with severity)
 */
export type getIncidentCandidatesResponse200 = {
  data: GetIncidentCandidatesResponse
  status: 200
}

export type getIncidentCandidatesResponse500 = {
  data: void
  status: 500
}
    
export type getIncidentCandidatesResponseSuccess = (getIncidentCandidatesResponse200) & {
  headers: Headers;
};
export type getIncidentCandidatesResponseError = (getIncidentCandidatesResponse500) & {
  headers: Headers;
};

export type getIncidentCandidatesResponse = (getIncidentCandidatesResponseSuccess | getIncidentCandidatesResponseError)

export const getGetIncidentCandidatesUrl = () => {


  

  return `/incidents/candidates`
}

export const getIncidentCandidates = async ( options?: RequestInit): Promise<getIncidentCandidatesResponse> => {
  
  return customInstance<getIncidentCandidatesResponse>(getGetIncidentCandidatesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetIncidentCandidatesQueryKey = () => {
    return [
    `/incidents/candidates`
    ] as const;
    }

    
export const getGetIncidentCandidatesQueryOptions = <TData = Awaited<ReturnType<typeof getIncidentCandidates>>, TError = ErrorType<void>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIncidentCandidates>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIncidentCandidatesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIncidentCandidates>>> = ({ signal }) => getIncidentCandidates({ signal });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIncidentCandidates>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetIncidentCandidatesQueryResult = NonNullable<Awaited<ReturnType<typeof getIncidentCandidates>>>
export type GetIncidentCandidatesQueryError = ErrorType<void>


export function useGetIncidentCandidates<TData = Awaited<ReturnType<typeof getIncidentCandidates>>, TError = ErrorType<void>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIncidentCandidates>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIncidentCandidates>>,
          TError,
          Awaited<ReturnType<typeof getIncidentCandidates>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIncidentCandidates<TData = Awaited<ReturnType<typeof getIncidentCandidates>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIncidentCandidates>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIncidentCandidates>>,
          TError,
          Awaited<ReturnType<typeof getIncidentCandidates>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIncidentCandidates<TData = Awaited<ReturnType<typeof getIncidentCandidates>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIncidentCandidates>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Incident candidates (down/degraded with severity)
 */

export function useGetIncidentCandidates<TData = Awaited<ReturnType<typeof getIncidentCandidates>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIncidentCandidates>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetIncidentCandidatesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
